name: ReminderCheck

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '0 */4 * * *'

jobs:
  # This workflow contains a single job called "check"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check HTTP
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://ackbot.vercel.app/api/check'
        method: 'GET'
        customHeaders: ${{ format('{{"X-Ackbot-Verify":"{0}"}}', secrets.ACKBOT_VERIFY) }}
